"""
Shared watchlist for simulation and live_signals.

Priority order:
  1. stock_screener/results/top_watchlist.json  — generated by the screener
  2. config.WATCHLIST                           — hardcoded fallback

Run the screener first to populate the watchlist:
  python stock_screener/run.py --cap midcap
  python stock_screener/run.py               (all 2000+ stocks, takes ~3 min)
"""

import json
import os
from datetime import datetime

import config
from stock_screener.report import WATCHLIST_PATH


def get_watchlist(top_n: int = 50) -> tuple[list[str], str]:
    """
    Returns (symbols, source_description).

    symbols            — list of NSE/BSE ticker strings
    source_description — human-readable string explaining where the list came from
    """
    if os.path.exists(WATCHLIST_PATH):
        with open(WATCHLIST_PATH) as f:
            data = json.load(f)

        generated_at = data.get("generated_at", "unknown")
        stocks       = data.get("stocks", [])
        symbols      = [s["symbol"] for s in stocks[:top_n]]

        # Warn if the screener file is more than 7 days old
        try:
            age_days = (datetime.now() - datetime.fromisoformat(generated_at)).days
            freshness = f"generated {age_days}d ago" if age_days > 0 else "generated today"
            if age_days > 7:
                freshness += "  ⚠ consider re-running the screener"
        except Exception:
            freshness = generated_at

        source = (
            f"screener top {len(symbols)}  "
            f"[dim](from {WATCHLIST_PATH}, {freshness})[/dim]"
        )
        return symbols, source

    # Fallback — screener has never been run
    symbols = config.WATCHLIST
    source  = (
        f"config.WATCHLIST ({len(symbols)} stocks)  "
        f"[dim][yellow]Run the screener to use scored stocks instead:[/yellow]  "
        f"python stock_screener/run.py[/dim]"
    )
    return symbols, source
