"""
US Stock Universe
-----------------
Hardcoded S&P 500 + NASDAQ 100 + Dow 30 stocks.
Web scraping is attempted first (with fallback to hardcoded list).
"""

import os
import logging
from dataclasses import dataclass

import pandas as pd

logger = logging.getLogger(__name__)

CACHE_DIR  = os.path.join(os.path.dirname(__file__), "data_cache")
os.makedirs(CACHE_DIR, exist_ok=True)


@dataclass(frozen=True)
class USStock:
    symbol: str
    name:   str
    sector: str
    index:  str   # "SP500" | "NASDAQ100" | "DOW30"


# ── Full S&P 500 + NASDAQ 100 + Dow 30 hardcoded ─────────────────────────────
# Format: (symbol, name, sector, index)
# Last updated: Apr 2026
_STOCKS = [
    # ── DOW 30 ────────────────────────────────────────────────────────────────
    ("AAPL",  "Apple Inc",                      "Technology",       "DOW30"),
    ("AMGN",  "Amgen Inc",                      "Healthcare",       "DOW30"),
    ("AXP",   "American Express",               "Financials",       "DOW30"),
    ("BA",    "Boeing Company",                 "Industrials",      "DOW30"),
    ("CAT",   "Caterpillar Inc",                "Industrials",      "DOW30"),
    ("CRM",   "Salesforce Inc",                 "Technology",       "DOW30"),
    ("CSCO",  "Cisco Systems",                  "Technology",       "DOW30"),
    ("CVX",   "Chevron Corporation",            "Energy",           "DOW30"),
    ("DIS",   "Walt Disney Company",            "Communication",    "DOW30"),
    ("DOW",   "Dow Inc",                        "Materials",        "DOW30"),
    ("GS",    "Goldman Sachs",                  "Financials",       "DOW30"),
    ("HD",    "Home Depot",                     "Consumer Disc",    "DOW30"),
    ("HON",   "Honeywell International",        "Industrials",      "DOW30"),
    ("IBM",   "IBM Corporation",                "Technology",       "DOW30"),
    ("INTC",  "Intel Corporation",              "Technology",       "DOW30"),
    ("JNJ",   "Johnson & Johnson",              "Healthcare",       "DOW30"),
    ("JPM",   "JPMorgan Chase",                 "Financials",       "DOW30"),
    ("KO",    "Coca-Cola Company",              "Consumer Staples", "DOW30"),
    ("MCD",   "McDonald's Corporation",         "Consumer Disc",    "DOW30"),
    ("MMM",   "3M Company",                     "Industrials",      "DOW30"),
    ("MRK",   "Merck & Co",                     "Healthcare",       "DOW30"),
    ("MSFT",  "Microsoft Corporation",          "Technology",       "DOW30"),
    ("NKE",   "Nike Inc",                       "Consumer Disc",    "DOW30"),
    ("PG",    "Procter & Gamble",               "Consumer Staples", "DOW30"),
    ("TRV",   "Travelers Companies",            "Financials",       "DOW30"),
    ("UNH",   "UnitedHealth Group",             "Healthcare",       "DOW30"),
    ("V",     "Visa Inc",                       "Financials",       "DOW30"),
    ("VZ",    "Verizon Communications",         "Communication",    "DOW30"),
    ("WMT",   "Walmart Inc",                    "Consumer Staples", "DOW30"),
    ("XOM",   "Exxon Mobil",                    "Energy",           "DOW30"),

    # ── NASDAQ 100 ────────────────────────────────────────────────────────────
    ("ADBE",  "Adobe Inc",                      "Technology",       "NASDAQ100"),
    ("ADI",   "Analog Devices",                 "Technology",       "NASDAQ100"),
    ("ADP",   "Automatic Data Processing",      "Technology",       "NASDAQ100"),
    ("ADSK",  "Autodesk Inc",                   "Technology",       "NASDAQ100"),
    ("AEP",   "American Electric Power",        "Utilities",        "NASDAQ100"),
    ("AMAT",  "Applied Materials",              "Technology",       "NASDAQ100"),
    ("AMD",   "Advanced Micro Devices",         "Technology",       "NASDAQ100"),
    ("AMZN",  "Amazon.com Inc",                 "Consumer Disc",    "NASDAQ100"),
    ("ANSS",  "ANSYS Inc",                      "Technology",       "NASDAQ100"),
    ("ARM",   "ARM Holdings",                   "Technology",       "NASDAQ100"),
    ("ASML",  "ASML Holding",                   "Technology",       "NASDAQ100"),
    ("AVGO",  "Broadcom Inc",                   "Technology",       "NASDAQ100"),
    ("AZN",   "AstraZeneca",                    "Healthcare",       "NASDAQ100"),
    ("BIIB",  "Biogen Inc",                     "Healthcare",       "NASDAQ100"),
    ("BKNG",  "Booking Holdings",               "Consumer Disc",    "NASDAQ100"),
    ("BKR",   "Baker Hughes",                   "Energy",           "NASDAQ100"),
    ("CCEP",  "Coca-Cola Europacific",          "Consumer Staples", "NASDAQ100"),
    ("CDNS",  "Cadence Design Systems",         "Technology",       "NASDAQ100"),
    ("CDW",   "CDW Corporation",                "Technology",       "NASDAQ100"),
    ("CEG",   "Constellation Energy",           "Utilities",        "NASDAQ100"),
    ("CHTR",  "Charter Communications",         "Communication",    "NASDAQ100"),
    ("CMCSA", "Comcast Corporation",            "Communication",    "NASDAQ100"),
    ("COST",  "Costco Wholesale",               "Consumer Staples", "NASDAQ100"),
    ("CPRT",  "Copart Inc",                     "Industrials",      "NASDAQ100"),
    ("CRWD",  "CrowdStrike Holdings",           "Technology",       "NASDAQ100"),
    ("CSCO",  "Cisco Systems",                  "Technology",       "NASDAQ100"),
    ("CSGP",  "CoStar Group",                   "Real Estate",      "NASDAQ100"),
    ("CSX",   "CSX Corporation",                "Industrials",      "NASDAQ100"),
    ("CTAS",  "Cintas Corporation",             "Industrials",      "NASDAQ100"),
    ("CTSH",  "Cognizant Technology",           "Technology",       "NASDAQ100"),
    ("DASH",  "DoorDash Inc",                   "Consumer Disc",    "NASDAQ100"),
    ("DDOG",  "Datadog Inc",                    "Technology",       "NASDAQ100"),
    ("DLTR",  "Dollar Tree",                    "Consumer Staples", "NASDAQ100"),
    ("DXCM",  "Dexcom Inc",                     "Healthcare",       "NASDAQ100"),
    ("EA",    "Electronic Arts",                "Communication",    "NASDAQ100"),
    ("EXC",   "Exelon Corporation",             "Utilities",        "NASDAQ100"),
    ("FANG",  "Diamondback Energy",             "Energy",           "NASDAQ100"),
    ("FAST",  "Fastenal Company",               "Industrials",      "NASDAQ100"),
    ("FTNT",  "Fortinet Inc",                   "Technology",       "NASDAQ100"),
    ("GEHC",  "GE HealthCare Technologies",     "Healthcare",       "NASDAQ100"),
    ("GFS",   "GlobalFoundries",                "Technology",       "NASDAQ100"),
    ("GILD",  "Gilead Sciences",                "Healthcare",       "NASDAQ100"),
    ("GOOG",  "Alphabet Inc (C)",               "Technology",       "NASDAQ100"),
    ("GOOGL", "Alphabet Inc (A)",               "Technology",       "NASDAQ100"),
    ("HON",   "Honeywell International",        "Industrials",      "NASDAQ100"),
    ("IDXX",  "IDEXX Laboratories",             "Healthcare",       "NASDAQ100"),
    ("ILMN",  "Illumina Inc",                   "Healthcare",       "NASDAQ100"),
    ("INTC",  "Intel Corporation",              "Technology",       "NASDAQ100"),
    ("INTU",  "Intuit Inc",                     "Technology",       "NASDAQ100"),
    ("ISRG",  "Intuitive Surgical",             "Healthcare",       "NASDAQ100"),
    ("KDP",   "Keurig Dr Pepper",               "Consumer Staples", "NASDAQ100"),
    ("KHC",   "Kraft Heinz Company",            "Consumer Staples", "NASDAQ100"),
    ("KLAC",  "KLA Corporation",                "Technology",       "NASDAQ100"),
    ("LIN",   "Linde plc",                      "Materials",        "NASDAQ100"),
    ("LRCX",  "Lam Research",                   "Technology",       "NASDAQ100"),
    ("LULU",  "Lululemon Athletica",            "Consumer Disc",    "NASDAQ100"),
    ("MAR",   "Marriott International",         "Consumer Disc",    "NASDAQ100"),
    ("MCHP",  "Microchip Technology",           "Technology",       "NASDAQ100"),
    ("MDB",   "MongoDB Inc",                    "Technology",       "NASDAQ100"),
    ("MDLZ",  "Mondelez International",         "Consumer Staples", "NASDAQ100"),
    ("MELI",  "MercadoLibre Inc",               "Consumer Disc",    "NASDAQ100"),
    ("META",  "Meta Platforms Inc",             "Technology",       "NASDAQ100"),
    ("MNST",  "Monster Beverage",               "Consumer Staples", "NASDAQ100"),
    ("MRVL",  "Marvell Technology",             "Technology",       "NASDAQ100"),
    ("MSTR",  "MicroStrategy",                  "Technology",       "NASDAQ100"),
    ("MU",    "Micron Technology",              "Technology",       "NASDAQ100"),
    ("NFLX",  "Netflix Inc",                    "Communication",    "NASDAQ100"),
    ("NVDA",  "NVIDIA Corporation",             "Technology",       "NASDAQ100"),
    ("NXPI",  "NXP Semiconductors",             "Technology",       "NASDAQ100"),
    ("ODFL",  "Old Dominion Freight",           "Industrials",      "NASDAQ100"),
    ("ON",    "ON Semiconductor",               "Technology",       "NASDAQ100"),
    ("ORLY",  "O'Reilly Automotive",            "Consumer Disc",    "NASDAQ100"),
    ("PANW",  "Palo Alto Networks",             "Technology",       "NASDAQ100"),
    ("PAYX",  "Paychex Inc",                    "Technology",       "NASDAQ100"),
    ("PCAR",  "PACCAR Inc",                     "Industrials",      "NASDAQ100"),
    ("PDD",   "PDD Holdings",                   "Consumer Disc",    "NASDAQ100"),
    ("PEP",   "PepsiCo Inc",                    "Consumer Staples", "NASDAQ100"),
    ("PLTR",  "Palantir Technologies",          "Technology",       "NASDAQ100"),
    ("PYPL",  "PayPal Holdings",                "Financials",       "NASDAQ100"),
    ("QCOM",  "Qualcomm Inc",                   "Technology",       "NASDAQ100"),
    ("REGN",  "Regeneron Pharmaceuticals",      "Healthcare",       "NASDAQ100"),
    ("ROP",   "Roper Technologies",             "Technology",       "NASDAQ100"),
    ("ROST",  "Ross Stores",                    "Consumer Disc",    "NASDAQ100"),
    ("SBUX",  "Starbucks Corporation",          "Consumer Disc",    "NASDAQ100"),
    ("SMCI",  "Super Micro Computer",           "Technology",       "NASDAQ100"),
    ("SNPS",  "Synopsys Inc",                   "Technology",       "NASDAQ100"),
    ("SPLK",  "Splunk Inc",                     "Technology",       "NASDAQ100"),
    ("TEAM",  "Atlassian Corporation",          "Technology",       "NASDAQ100"),
    ("TMUS",  "T-Mobile US",                    "Communication",    "NASDAQ100"),
    ("TSLA",  "Tesla Inc",                      "Consumer Disc",    "NASDAQ100"),
    ("TTD",   "The Trade Desk",                 "Technology",       "NASDAQ100"),
    ("TXN",   "Texas Instruments",              "Technology",       "NASDAQ100"),
    ("VRSK",  "Verisk Analytics",               "Industrials",      "NASDAQ100"),
    ("VRTX",  "Vertex Pharmaceuticals",         "Healthcare",       "NASDAQ100"),
    ("WBA",   "Walgreens Boots Alliance",       "Consumer Staples", "NASDAQ100"),
    ("WBD",   "Warner Bros Discovery",          "Communication",    "NASDAQ100"),
    ("WDAY",  "Workday Inc",                    "Technology",       "NASDAQ100"),
    ("XEL",   "Xcel Energy",                    "Utilities",        "NASDAQ100"),
    ("ZS",    "Zscaler Inc",                    "Technology",       "NASDAQ100"),

    # ── S&P 500 (additional beyond DOW/NASDAQ) ────────────────────────────────
    ("A",     "Agilent Technologies",           "Healthcare",       "SP500"),
    ("AAL",   "American Airlines",              "Industrials",      "SP500"),
    ("AAP",   "Advance Auto Parts",             "Consumer Disc",    "SP500"),
    ("ABBV",  "AbbVie Inc",                     "Healthcare",       "SP500"),
    ("ABT",   "Abbott Laboratories",            "Healthcare",       "SP500"),
    ("ACN",   "Accenture plc",                  "Technology",       "SP500"),
    ("ADSK",  "Autodesk Inc",                   "Technology",       "SP500"),
    ("AIG",   "American International Group",   "Financials",       "SP500"),
    ("AIZ",   "Assurant Inc",                   "Financials",       "SP500"),
    ("AJG",   "Arthur J. Gallagher",            "Financials",       "SP500"),
    ("AKAM",  "Akamai Technologies",            "Technology",       "SP500"),
    ("ALB",   "Albemarle Corporation",          "Materials",        "SP500"),
    ("ALGN",  "Align Technology",               "Healthcare",       "SP500"),
    ("ALL",   "Allstate Corporation",           "Financials",       "SP500"),
    ("ALLE",  "Allegion plc",                   "Industrials",      "SP500"),
    ("ANET",  "Arista Networks",                "Technology",       "SP500"),
    ("AON",   "Aon plc",                        "Financials",       "SP500"),
    ("AOS",   "A. O. Smith",                    "Industrials",      "SP500"),
    ("APD",   "Air Products & Chemicals",       "Materials",        "SP500"),
    ("APH",   "Amphenol Corporation",           "Technology",       "SP500"),
    ("ARE",   "Alexandria Real Estate",         "Real Estate",      "SP500"),
    ("ATO",   "Atmos Energy",                   "Utilities",        "SP500"),
    ("AVB",   "AvalonBay Communities",          "Real Estate",      "SP500"),
    ("AVGO",  "Broadcom Inc",                   "Technology",       "SP500"),
    ("AVY",   "Avery Dennison",                 "Materials",        "SP500"),
    ("AWK",   "American Water Works",           "Utilities",        "SP500"),
    ("BAC",   "Bank of America",                "Financials",       "SP500"),
    ("BALL",  "Ball Corporation",               "Materials",        "SP500"),
    ("BDX",   "Becton Dickinson",               "Healthcare",       "SP500"),
    ("BEN",   "Franklin Resources",             "Financials",       "SP500"),
    ("BIO",   "Bio-Rad Laboratories",           "Healthcare",       "SP500"),
    ("BK",    "Bank of New York Mellon",        "Financials",       "SP500"),
    ("BMY",   "Bristol-Myers Squibb",           "Healthcare",       "SP500"),
    ("BRK-B", "Berkshire Hathaway B",           "Financials",       "SP500"),
    ("BSX",   "Boston Scientific",              "Healthcare",       "SP500"),
    ("BWA",   "BorgWarner Inc",                 "Consumer Disc",    "SP500"),
    ("C",     "Citigroup Inc",                  "Financials",       "SP500"),
    ("CAG",   "Conagra Brands",                 "Consumer Staples", "SP500"),
    ("CB",    "Chubb Limited",                  "Financials",       "SP500"),
    ("CBOE",  "Cboe Global Markets",            "Financials",       "SP500"),
    ("CBRE",  "CBRE Group",                     "Real Estate",      "SP500"),
    ("CF",    "CF Industries",                  "Materials",        "SP500"),
    ("CFG",   "Citizens Financial",             "Financials",       "SP500"),
    ("CHD",   "Church & Dwight",                "Consumer Staples", "SP500"),
    ("CHK",   "Chesapeake Energy",              "Energy",           "SP500"),
    ("CL",    "Colgate-Palmolive",              "Consumer Staples", "SP500"),
    ("CLX",   "Clorox Company",                 "Consumer Staples", "SP500"),
    ("CMA",   "Comerica Inc",                   "Financials",       "SP500"),
    ("CME",   "CME Group",                      "Financials",       "SP500"),
    ("CMG",   "Chipotle Mexican Grill",         "Consumer Disc",    "SP500"),
    ("CMI",   "Cummins Inc",                    "Industrials",      "SP500"),
    ("CMS",   "CMS Energy",                     "Utilities",        "SP500"),
    ("CNC",   "Centene Corporation",            "Healthcare",       "SP500"),
    ("CNP",   "CenterPoint Energy",             "Utilities",        "SP500"),
    ("COF",   "Capital One Financial",          "Financials",       "SP500"),
    ("COO",   "Cooper Companies",               "Healthcare",       "SP500"),
    ("COP",   "ConocoPhillips",                 "Energy",           "SP500"),
    ("CPB",   "Campbell Soup",                  "Consumer Staples", "SP500"),
    ("CPT",   "Camden Property Trust",          "Real Estate",      "SP500"),
    ("CRL",   "Charles River Labs",             "Healthcare",       "SP500"),
    ("CTVA",  "Corteva Inc",                    "Materials",        "SP500"),
    ("D",     "Dominion Energy",                "Utilities",        "SP500"),
    ("DAL",   "Delta Air Lines",                "Industrials",      "SP500"),
    ("DD",    "DuPont de Nemours",              "Materials",        "SP500"),
    ("DE",    "Deere & Company",                "Industrials",      "SP500"),
    ("DG",    "Dollar General",                 "Consumer Staples", "SP500"),
    ("DHI",   "D.R. Horton",                    "Consumer Disc",    "SP500"),
    ("DHR",   "Danaher Corporation",            "Healthcare",       "SP500"),
    ("DKS",   "Dick's Sporting Goods",          "Consumer Disc",    "SP500"),
    ("DLR",   "Digital Realty Trust",           "Real Estate",      "SP500"),
    ("DXCM",  "Dexcom Inc",                     "Healthcare",       "SP500"),
    ("DXC",   "DXC Technology",                 "Technology",       "SP500"),
    ("ED",    "Consolidated Edison",            "Utilities",        "SP500"),
    ("EFX",   "Equifax Inc",                    "Industrials",      "SP500"),
    ("EIX",   "Edison International",           "Utilities",        "SP500"),
    ("EL",    "Estée Lauder",                   "Consumer Staples", "SP500"),
    ("EMN",   "Eastman Chemical",               "Materials",        "SP500"),
    ("EMR",   "Emerson Electric",               "Industrials",      "SP500"),
    ("EOG",   "EOG Resources",                  "Energy",           "SP500"),
    ("EQR",   "Equity Residential",             "Real Estate",      "SP500"),
    ("ES",    "Eversource Energy",              "Utilities",        "SP500"),
    ("ESS",   "Essex Property Trust",           "Real Estate",      "SP500"),
    ("ETN",   "Eaton Corporation",              "Industrials",      "SP500"),
    ("ETR",   "Entergy Corporation",            "Utilities",        "SP500"),
    ("EVRG",  "Evergy Inc",                     "Utilities",        "SP500"),
    ("EW",    "Edwards Lifesciences",           "Healthcare",       "SP500"),
    ("EXR",   "Extra Space Storage",            "Real Estate",      "SP500"),
    ("F",     "Ford Motor Company",             "Consumer Disc",    "SP500"),
    ("FANG",  "Diamondback Energy",             "Energy",           "SP500"),
    ("FDS",   "FactSet Research",               "Financials",       "SP500"),
    ("FDX",   "FedEx Corporation",              "Industrials",      "SP500"),
    ("FE",    "FirstEnergy Corp",               "Utilities",        "SP500"),
    ("FFIV",  "F5 Inc",                         "Technology",       "SP500"),
    ("FI",    "Fiserv Inc",                     "Technology",       "SP500"),
    ("FIS",   "Fidelity National Info",         "Technology",       "SP500"),
    ("FLT",   "Fleetcor Technologies",          "Technology",       "SP500"),
    ("FMC",   "FMC Corporation",                "Materials",        "SP500"),
    ("FOX",   "Fox Corporation",                "Communication",    "SP500"),
    ("FRT",   "Federal Realty Investment",      "Real Estate",      "SP500"),
    ("FSLR",  "First Solar Inc",                "Technology",       "SP500"),
    ("GD",    "General Dynamics",               "Industrials",      "SP500"),
    ("GE",    "GE Aerospace",                   "Industrials",      "SP500"),
    ("GEHC",  "GE HealthCare",                  "Healthcare",       "SP500"),
    ("GEN",   "Gen Digital Inc",                "Technology",       "SP500"),
    ("GILD",  "Gilead Sciences",                "Healthcare",       "SP500"),
    ("GL",    "Globe Life Inc",                 "Financials",       "SP500"),
    ("GLW",   "Corning Inc",                    "Technology",       "SP500"),
    ("GM",    "General Motors",                 "Consumer Disc",    "SP500"),
    ("GNRC",  "Generac Holdings",               "Industrials",      "SP500"),
    ("GPC",   "Genuine Parts Company",          "Consumer Disc",    "SP500"),
    ("GPN",   "Global Payments",                "Technology",       "SP500"),
    ("GRMN",  "Garmin Ltd",                     "Technology",       "SP500"),
    ("GWW",   "W.W. Grainger",                  "Industrials",      "SP500"),
    ("HAL",   "Halliburton Company",            "Energy",           "SP500"),
    ("HAS",   "Hasbro Inc",                     "Consumer Disc",    "SP500"),
    ("HBAN",  "Huntington Bancshares",          "Financials",       "SP500"),
    ("HCA",   "HCA Healthcare",                 "Healthcare",       "SP500"),
    ("HES",   "Hess Corporation",               "Energy",           "SP500"),
    ("HIG",   "Hartford Financial",             "Financials",       "SP500"),
    ("HII",   "Huntington Ingalls",             "Industrials",      "SP500"),
    ("HLT",   "Hilton Worldwide",               "Consumer Disc",    "SP500"),
    ("HRL",   "Hormel Foods",                   "Consumer Staples", "SP500"),
    ("HSIC",  "Henry Schein",                   "Healthcare",       "SP500"),
    ("HST",   "Host Hotels & Resorts",          "Real Estate",      "SP500"),
    ("HSY",   "Hershey Company",                "Consumer Staples", "SP500"),
    ("HUM",   "Humana Inc",                     "Healthcare",       "SP500"),
    ("HWM",   "Howmet Aerospace",               "Industrials",      "SP500"),
    ("ICE",   "Intercontinental Exchange",      "Financials",       "SP500"),
    ("IEX",   "IDEX Corporation",               "Industrials",      "SP500"),
    ("IFF",   "Intl Flavors & Fragrances",      "Materials",        "SP500"),
    ("INCY",  "Incyte Corporation",             "Healthcare",       "SP500"),
    ("IPG",   "Interpublic Group",              "Communication",    "SP500"),
    ("IQV",   "IQVIA Holdings",                 "Healthcare",       "SP500"),
    ("IR",    "Ingersoll Rand",                 "Industrials",      "SP500"),
    ("IRM",   "Iron Mountain",                  "Real Estate",      "SP500"),
    ("IT",    "Gartner Inc",                    "Technology",       "SP500"),
    ("ITW",   "Illinois Tool Works",            "Industrials",      "SP500"),
    ("IVZ",   "Invesco Ltd",                    "Financials",       "SP500"),
    ("J",     "Jacobs Solutions",               "Industrials",      "SP500"),
    ("JBHT",  "J.B. Hunt Transport",            "Industrials",      "SP500"),
    ("JCI",   "Johnson Controls",               "Industrials",      "SP500"),
    ("JKHY",  "Jack Henry & Associates",        "Technology",       "SP500"),
    ("JNJ",   "Johnson & Johnson",              "Healthcare",       "SP500"),
    ("JNPR",  "Juniper Networks",               "Technology",       "SP500"),
    ("K",     "Kellanova",                      "Consumer Staples", "SP500"),
    ("KEY",   "KeyCorp",                        "Financials",       "SP500"),
    ("KEYS",  "Keysight Technologies",          "Technology",       "SP500"),
    ("KIM",   "Kimco Realty",                   "Real Estate",      "SP500"),
    ("KMB",   "Kimberly-Clark",                 "Consumer Staples", "SP500"),
    ("KMI",   "Kinder Morgan",                  "Energy",           "SP500"),
    ("KVUE",  "Kenvue Inc",                     "Consumer Staples", "SP500"),
    ("L",     "Loews Corporation",              "Financials",       "SP500"),
    ("LEN",   "Lennar Corporation",             "Consumer Disc",    "SP500"),
    ("LH",    "LabCorp",                        "Healthcare",       "SP500"),
    ("LHX",   "L3Harris Technologies",          "Industrials",      "SP500"),
    ("LKQ",   "LKQ Corporation",                "Consumer Disc",    "SP500"),
    ("LLY",   "Eli Lilly",                      "Healthcare",       "SP500"),
    ("LMT",   "Lockheed Martin",                "Industrials",      "SP500"),
    ("LNT",   "Alliant Energy",                 "Utilities",        "SP500"),
    ("LOW",   "Lowe's Companies",               "Consumer Disc",    "SP500"),
    ("LUMN",  "Lumen Technologies",             "Communication",    "SP500"),
    ("LUV",   "Southwest Airlines",             "Industrials",      "SP500"),
    ("LVS",   "Las Vegas Sands",                "Consumer Disc",    "SP500"),
    ("LYB",   "LyondellBasell",                 "Materials",        "SP500"),
    ("LYV",   "Live Nation Entertainment",      "Communication",    "SP500"),
    ("MA",    "Mastercard Inc",                 "Financials",       "SP500"),
    ("MAA",   "Mid-America Apartment",          "Real Estate",      "SP500"),
    ("MAS",   "Masco Corporation",              "Industrials",      "SP500"),
    ("MCD",   "McDonald's Corporation",         "Consumer Disc",    "SP500"),
    ("MCK",   "McKesson Corporation",           "Healthcare",       "SP500"),
    ("MCO",   "Moody's Corporation",            "Financials",       "SP500"),
    ("MDLZ",  "Mondelez International",         "Consumer Staples", "SP500"),
    ("MDT",   "Medtronic plc",                  "Healthcare",       "SP500"),
    ("MGM",   "MGM Resorts",                    "Consumer Disc",    "SP500"),
    ("MHK",   "Mohawk Industries",              "Consumer Disc",    "SP500"),
    ("MKC",   "McCormick & Company",            "Consumer Staples", "SP500"),
    ("MLM",   "Martin Marietta",                "Materials",        "SP500"),
    ("MMC",   "Marsh & McLennan",               "Financials",       "SP500"),
    ("MO",    "Altria Group",                   "Consumer Staples", "SP500"),
    ("MOH",   "Molina Healthcare",              "Healthcare",       "SP500"),
    ("MOS",   "Mosaic Company",                 "Materials",        "SP500"),
    ("MPC",   "Marathon Petroleum",             "Energy",           "SP500"),
    ("MPWR",  "Monolithic Power Systems",       "Technology",       "SP500"),
    ("MRO",   "Marathon Oil",                   "Energy",           "SP500"),
    ("MS",    "Morgan Stanley",                 "Financials",       "SP500"),
    ("MSI",   "Motorola Solutions",             "Technology",       "SP500"),
    ("MTB",   "M&T Bank",                       "Financials",       "SP500"),
    ("MTD",   "Mettler-Toledo",                 "Healthcare",       "SP500"),
    ("MU",    "Micron Technology",              "Technology",       "SP500"),
    ("NEE",   "NextEra Energy",                 "Utilities",        "SP500"),
    ("NEM",   "Newmont Corporation",            "Materials",        "SP500"),
    ("NI",    "NiSource Inc",                   "Utilities",        "SP500"),
    ("NKE",   "Nike Inc",                       "Consumer Disc",    "SP500"),
    ("NOC",   "Northrop Grumman",               "Industrials",      "SP500"),
    ("NOW",   "ServiceNow Inc",                 "Technology",       "SP500"),
    ("NSC",   "Norfolk Southern",               "Industrials",      "SP500"),
    ("NTRS",  "Northern Trust",                 "Financials",       "SP500"),
    ("NUE",   "Nucor Corporation",              "Materials",        "SP500"),
    ("NVDA",  "NVIDIA Corporation",             "Technology",       "SP500"),
    ("NVR",   "NVR Inc",                        "Consumer Disc",    "SP500"),
    ("NWS",   "News Corporation",               "Communication",    "SP500"),
    ("O",     "Realty Income",                  "Real Estate",      "SP500"),
    ("OKE",   "ONEOK Inc",                      "Energy",           "SP500"),
    ("OMC",   "Omnicom Group",                  "Communication",    "SP500"),
    ("ORCL",  "Oracle Corporation",             "Technology",       "SP500"),
    ("OTIS",  "Otis Worldwide",                 "Industrials",      "SP500"),
    ("OXY",   "Occidental Petroleum",           "Energy",           "SP500"),
    ("PAYC",  "Paycom Software",                "Technology",       "SP500"),
    ("PCAR",  "PACCAR Inc",                     "Industrials",      "SP500"),
    ("PCG",   "PG&E Corporation",               "Utilities",        "SP500"),
    ("PEAK",  "Healthpeak Properties",          "Real Estate",      "SP500"),
    ("PFE",   "Pfizer Inc",                     "Healthcare",       "SP500"),
    ("PFG",   "Principal Financial",            "Financials",       "SP500"),
    ("PHM",   "PulteGroup Inc",                 "Consumer Disc",    "SP500"),
    ("PKG",   "Packaging Corp of America",      "Materials",        "SP500"),
    ("PLD",   "Prologis Inc",                   "Real Estate",      "SP500"),
    ("PM",    "Philip Morris International",    "Consumer Staples", "SP500"),
    ("PNC",   "PNC Financial Services",         "Financials",       "SP500"),
    ("PNR",   "Pentair plc",                    "Industrials",      "SP500"),
    ("PNW",   "Pinnacle West Capital",          "Utilities",        "SP500"),
    ("POOL",  "Pool Corporation",               "Consumer Disc",    "SP500"),
    ("PPG",   "PPG Industries",                 "Materials",        "SP500"),
    ("PPL",   "PPL Corporation",                "Utilities",        "SP500"),
    ("PRU",   "Prudential Financial",           "Financials",       "SP500"),
    ("PSA",   "Public Storage",                 "Real Estate",      "SP500"),
    ("PSX",   "Phillips 66",                    "Energy",           "SP500"),
    ("PTC",   "PTC Inc",                        "Technology",       "SP500"),
    ("PWR",   "Quanta Services",                "Industrials",      "SP500"),
    ("PXD",   "Pioneer Natural Resources",      "Energy",           "SP500"),
    ("QRVO",  "Qorvo Inc",                      "Technology",       "SP500"),
    ("RCL",   "Royal Caribbean",                "Consumer Disc",    "SP500"),
    ("RE",    "Everest Group",                  "Financials",       "SP500"),
    ("REG",   "Regency Centers",                "Real Estate",      "SP500"),
    ("RF",    "Regions Financial",              "Financials",       "SP500"),
    ("RJF",   "Raymond James Financial",        "Financials",       "SP500"),
    ("RL",    "Ralph Lauren",                   "Consumer Disc",    "SP500"),
    ("RMD",   "ResMed Inc",                     "Healthcare",       "SP500"),
    ("ROK",   "Rockwell Automation",            "Industrials",      "SP500"),
    ("ROL",   "Rollins Inc",                    "Industrials",      "SP500"),
    ("ROP",   "Roper Technologies",             "Technology",       "SP500"),
    ("ROST",  "Ross Stores",                    "Consumer Disc",    "SP500"),
    ("RSG",   "Republic Services",              "Industrials",      "SP500"),
    ("RTX",   "RTX Corporation",                "Industrials",      "SP500"),
    ("SBAC",  "SBA Communications",             "Real Estate",      "SP500"),
    ("SBUX",  "Starbucks Corporation",          "Consumer Disc",    "SP500"),
    ("SCHW",  "Charles Schwab",                 "Financials",       "SP500"),
    ("SHW",   "Sherwin-Williams",               "Materials",        "SP500"),
    ("SJM",   "J.M. Smucker",                   "Consumer Staples", "SP500"),
    ("SLB",   "Schlumberger",                   "Energy",           "SP500"),
    ("SNA",   "Snap-on Incorporated",           "Industrials",      "SP500"),
    ("SNDR",  "Schneider National",             "Industrials",      "SP500"),
    ("SO",    "Southern Company",               "Utilities",        "SP500"),
    ("SPG",   "Simon Property Group",           "Real Estate",      "SP500"),
    ("SPGI",  "S&P Global Inc",                 "Financials",       "SP500"),
    ("SRE",   "Sempra Energy",                  "Utilities",        "SP500"),
    ("STT",   "State Street",                   "Financials",       "SP500"),
    ("STX",   "Seagate Technology",             "Technology",       "SP500"),
    ("STZ",   "Constellation Brands",           "Consumer Staples", "SP500"),
    ("SWK",   "Stanley Black & Decker",         "Industrials",      "SP500"),
    ("SWKS",  "Skyworks Solutions",             "Technology",       "SP500"),
    ("SYF",   "Synchrony Financial",            "Financials",       "SP500"),
    ("SYK",   "Stryker Corporation",            "Healthcare",       "SP500"),
    ("SYY",   "Sysco Corporation",              "Consumer Staples", "SP500"),
    ("T",     "AT&T Inc",                       "Communication",    "SP500"),
    ("TAP",   "Molson Coors Beverage",          "Consumer Staples", "SP500"),
    ("TDG",   "TransDigm Group",                "Industrials",      "SP500"),
    ("TDY",   "Teledyne Technologies",          "Technology",       "SP500"),
    ("TECH",  "Bio-Techne Corporation",         "Healthcare",       "SP500"),
    ("TEL",   "TE Connectivity",                "Technology",       "SP500"),
    ("TER",   "Teradyne Inc",                   "Technology",       "SP500"),
    ("TFC",   "Truist Financial",               "Financials",       "SP500"),
    ("TFX",   "Teleflex Inc",                   "Healthcare",       "SP500"),
    ("TGT",   "Target Corporation",             "Consumer Staples", "SP500"),
    ("TJX",   "TJX Companies",                  "Consumer Disc",    "SP500"),
    ("TMO",   "Thermo Fisher Scientific",       "Healthcare",       "SP500"),
    ("TRMB",  "Trimble Inc",                    "Technology",       "SP500"),
    ("TROW",  "T. Rowe Price",                  "Financials",       "SP500"),
    ("TRV",   "Travelers Companies",            "Financials",       "SP500"),
    ("TSCO",  "Tractor Supply Company",         "Consumer Disc",    "SP500"),
    ("TSN",   "Tyson Foods",                    "Consumer Staples", "SP500"),
    ("TT",    "Trane Technologies",             "Industrials",      "SP500"),
    ("TTWO",  "Take-Two Interactive",           "Communication",    "SP500"),
    ("TXT",   "Textron Inc",                    "Industrials",      "SP500"),
    ("UAL",   "United Airlines",                "Industrials",      "SP500"),
    ("UDR",   "United Dominion Realty",         "Real Estate",      "SP500"),
    ("UHS",   "Universal Health Services",      "Healthcare",       "SP500"),
    ("ULTA",  "Ulta Beauty",                    "Consumer Disc",    "SP500"),
    ("UNP",   "Union Pacific",                  "Industrials",      "SP500"),
    ("UPS",   "United Parcel Service",          "Industrials",      "SP500"),
    ("URI",   "United Rentals",                 "Industrials",      "SP500"),
    ("USB",   "U.S. Bancorp",                   "Financials",       "SP500"),
    ("VFC",   "VF Corporation",                 "Consumer Disc",    "SP500"),
    ("VLO",   "Valero Energy",                  "Energy",           "SP500"),
    ("VMC",   "Vulcan Materials",               "Materials",        "SP500"),
    ("VRSN",  "VeriSign Inc",                   "Technology",       "SP500"),
    ("VRTX",  "Vertex Pharmaceuticals",         "Healthcare",       "SP500"),
    ("VTR",   "Ventas Inc",                     "Real Estate",      "SP500"),
    ("WAB",   "Wabtec Corporation",             "Industrials",      "SP500"),
    ("WAT",   "Waters Corporation",             "Healthcare",       "SP500"),
    ("WEC",   "WEC Energy Group",               "Utilities",        "SP500"),
    ("WELL",  "Welltower Inc",                  "Real Estate",      "SP500"),
    ("WFC",   "Wells Fargo",                    "Financials",       "SP500"),
    ("WHR",   "Whirlpool Corporation",          "Consumer Disc",    "SP500"),
    ("WM",    "Waste Management",               "Industrials",      "SP500"),
    ("WMB",   "Williams Companies",             "Energy",           "SP500"),
    ("WRB",   "W. R. Berkley",                  "Financials",       "SP500"),
    ("WRK",   "WestRock Company",               "Materials",        "SP500"),
    ("WST",   "West Pharmaceutical Services",   "Healthcare",       "SP500"),
    ("WY",    "Weyerhaeuser Company",           "Real Estate",      "SP500"),
    ("XYL",   "Xylem Inc",                      "Industrials",      "SP500"),
    ("YUM",   "Yum! Brands",                    "Consumer Disc",    "SP500"),
    ("ZBH",   "Zimmer Biomet",                  "Healthcare",       "SP500"),
    ("ZBRA",  "Zebra Technologies",             "Technology",       "SP500"),
    ("ZTS",   "Zoetis Inc",                     "Healthcare",       "SP500"),

    # ── Popular / trending ────────────────────────────────────────────────────
    ("COIN",  "Coinbase Global",                "Financials",       "SP500"),
    ("HOOD",  "Robinhood Markets",              "Financials",       "SP500"),
    ("PLTR",  "Palantir Technologies",          "Technology",       "SP500"),
    ("RBLX",  "Roblox Corporation",             "Communication",    "SP500"),
    ("RIVN",  "Rivian Automotive",              "Consumer Disc",    "SP500"),
    ("SOFI",  "SoFi Technologies",              "Financials",       "SP500"),
    ("SPOT",  "Spotify Technology",             "Communication",    "NASDAQ100"),
    ("UBER",  "Uber Technologies",              "Technology",       "SP500"),
    ("U",     "Unity Software",                 "Technology",       "SP500"),
]


def get_us_universe() -> list[USStock]:
    # Deduplicate by symbol (keep first occurrence)
    seen: set[str] = set()
    result = []
    for sym, name, sector, index in _STOCKS:
        if sym not in seen:
            seen.add(sym)
            result.append(USStock(symbol=sym, name=name, sector=sector, index=index))
    return result
